### ISSUE TITLE
Override MessageTemplate defaults

### ISSUE THREAD

**Issue by PureBasics** [DEHuckaKpyT/telegram-bot#2]
Is it currently possible to override the default messages in MessageTemplate? If not, this would be a nice feature.

Alternatively, a switch to English would also be appreciated.

**Comment by DEHuckaKpyT** [comment]
Yes, of course. You can change the default messages in this way:

```kotlin
class CustomMessageTemplate : MessageTemplate(
    whenCommandNotFound = "test message command not found"
)

val config = TelegramBotConfig().apply {
    receiving {
        messageTemplate = { CustomMessageTemplate() }
    }
}
```

**Comment by DEHuckaKpyT** [comment]
> Alternatively, a switch to English would also be appreciated.

You're right. It will be fixed for sure.

**Comment by DEHuckaKpyT** [comment]
@PureBasics, it's also in the [documentation](https://dehuckakpyt.github.io/telegram-bot/exception-handling.html)
