### ISSUE TITLE
Vulnerability found in dependency: Cxeb68d52e-5509 3.7

### ISSUE THREAD

**Issue by xDilettante** [DEHuckaKpyT/telegram-bot#5]
IDE - JtBrains IDEA Reports a vulnerability in the module

Vulnerability found in dependency:
Cxeb68d52e-5509
3.7
Transitive Exposure of Sensitive Information to an Unauthorized Actor vulnerability with Low severity found

implementation("io.github.dehuckakpyt.telegrambot:telegram-bot-core:0.10.1")

**Comment by DEHuckaKpyT** [comment]
Thanks for the issue. Yeah, it's showing up like that too. Now let me fix it quickly. 

And in general I plan to update the dependencies in the project in the near future.
