### ISSUE TITLE
Can JpaTelegramMessage save InlineKeyboardMarkup when editing a message?

### ISSUE THREAD

**Issue by kukume** [DEHuckaKpyT/telegram-bot#6]
Can JpaTelegramMessage save InlineKeyboardMarkup when editing a message?

**Comment by DEHuckaKpyT** [comment]
Not at the moment.

But there are plans to refactor message saving. Roughly I see it like this:
Was:
```
interface MessageSource {

    suspend fun save(chatId: Long, fromId: Long, fromBot: Boolean, messageId: Long, type: String, text: String?, fileIds: List<String>?)
}
```
will be:
```
interface MessageSource {

    suspend fun save(message: Message, fromBot: Boolean)
}
```

This will allow you to save whatever you want from a message.

**Comment by DEHuckaKpyT** [comment]
Time is tight at the moment. I can do some sort of temporary solution within a week. But presumably with the final MessageSource version.

**Comment by DEHuckaKpyT** [comment]
I looked at your PR and it seemed to me that it would be difficult to maintain. I propose a more flexible solution, even though it's a bit more complicated.

If you're happy with this option, I'll merge the PR in the near future.

**Comment by kukume** [comment]
I solve it temporarily.

**Comment by kukume** [comment]
#8 I think it's OK.
